# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubebuilderInitializerPlugin < Formula
  desc ""
  homepage "https://github.com/astrokube/homebrew-tools"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/astrokube/kubebuilder-initializer-plugin/releases/download/v0.1.0/kubebuilder-initializer-plugin_0.1.0_darwin_amd64.tar.gz"
      sha256 "b3cdbeb1cb267bffbe7e8a5066a708c2dfaf2fce0ffa65344cfa513d5f9e7804"

      def install
        bin.install "kubebuilder-initializer-plugin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/astrokube/kubebuilder-initializer-plugin/releases/download/v0.1.0/kubebuilder-initializer-plugin_0.1.0_darwin_arm64.tar.gz"
      sha256 "2be43d46975d6e64709512bef8647da6e5174451dccc64896b00ef73067f1591"

      def install
        bin.install "kubebuilder-initializer-plugin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astrokube/kubebuilder-initializer-plugin/releases/download/v0.1.0/kubebuilder-initializer-plugin_0.1.0_linux_arm64.tar.gz"
      sha256 "bd30fcf006e3b9a6b8b8d51562168819397e32991fef27fe32e84711d69fb3df"

      def install
        bin.install "kubebuilder-initializer-plugin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/astrokube/kubebuilder-initializer-plugin/releases/download/v0.1.0/kubebuilder-initializer-plugin_0.1.0_linux_amd64.tar.gz"
      sha256 "0d5e642c84eeae0592ad398e161b23d0ec87898e972068055c6fee1dee814356"

      def install
        bin.install "kubebuilder-initializer-plugin"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/astrokube/kubebuilder-initializer-plugin/releases/download/v0.1.0/kubebuilder-initializer-plugin_0.1.0_linux_armv6.tar.gz"
      sha256 "fdb05d34e99a8339251261cb8717adc345fa9ae7146b792bdc6d5d61d25442f9"

      def install
        bin.install "kubebuilder-initializer-plugin"
      end
    end
  end
end
